# Load necessary libraries
suppressMessages({
  library(Seurat)
  library(Matrix)
  library(scater)
  library(org.Hs.eg.db)
  library(dplyr)
  library(SingleCellExperiment)
  library(ggplot2)
  library(RColorBrewer)
  library(NMF)
  library(ggrepel)
  library(edgeR)

})
# Source custom scripts
source("BETi-COVIDHeart/utilities/ggplotColors.R") 
source("BETi-COVIDHeart/utilities/normCounts.R")  

#--------Read in snRNAseq data of human cardiac organoids (hCO) generated by Mills et al. 2021 [EGAS00001005174]------------
organoids <- Read10X(data.dir = "./hCOs/filtered_feature_bc_matrix/")
dim(organoids)

###In this section we are going to produce several quality control plots and also remove low quality cells and non-informative genes.

##Creat a seurat object 
organoids.seurat <- CreateSeuratObject(counts  = organoids, project = "hCOs")
##Gene annotation
ann <- AnnotationDbi::select(org.Hs.eg.db,keys=rownames(organoids.seurat),columns=c("SYMBOL","ENTREZID","ENSEMBL","GENENAME"),keytype = "SYMBOL")
m <- match(rownames(organoids.seurat),ann$SYMBOL)
ann <- ann[m,]
table(ann$SYMBOL==rownames(organoids.seurat))
mito <- grep("mitochondrial",ann$GENENAME)
length(mito)
ribo <- grep("ribosomal",ann$GENENAME)
length(ribo)
missingEZID <- which(is.na(ann$ENTREZID))
length(missingEZID)

##Basic QC-----------
mito.counts <- colSums(organoids.seurat[mito, ])
pct.mito <- mito.counts/organoids.seurat$nCount_RNA*100
organoids.seurat <- AddMetaData(organoids.seurat, pct.mito, col.name = "percent.mito")
ribo.counts <- colSums(organoids.seurat[ribo, ])
pct.ribo <- ribo.counts/organoids.seurat$nCount_RNA*100
organoids.seurat <- AddMetaData(organoids.seurat, pct.ribo, col.name = "percent.ribo")
pz <- colMeans(organoids.seurat@assays$RNA@counts==0)
organoids.seurat <- AddMetaData(organoids.seurat, pz, col.name = "proportion.zeroes")

##Plot QC --------------
par(mfrow=c(1,3))
plot(density(organoids.seurat$nCount_RNA),main="Distribution of library sizes")
abline(v=2500,col=2)
legend("topright",lty=2,col=4,legend="2500 library size")
plot(density(pz), main="Distribution of proportion of zeroes per cell", cex.main=1)
abline(v=0.95,col=2)
legend("topright",lty=2,col=4,legend="0.95 proportion of zeroes/cell")
plot(density(organoids.seurat$nFeature_RNA), main="Distribution of detected genes per cell", cex.main=1)
abline(v=500,col=4, lty=3)
legend("topright",lty=2,col=4,legend="500 genes")
VlnPlot(organoids.seurat, features = "nFeature_RNA", pt.size = 0.1) + NoLegend()
VlnPlot(organoids.seurat, features = "nCount_RNA", pt.size = 0.1) + NoLegend()
VlnPlot(organoids.seurat, features = "percent.mito", pt.size = 0.1) + NoLegend()
VlnPlot(organoids.seurat, features = "percent.ribo", pt.size = 0.1) + NoLegend()
VlnPlot(organoids.seurat, features = "proportion.zeroes", pt.size = 0.1) + NoLegend()
FeatureScatter(organoids.seurat, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
FeatureScatter(organoids.seurat, feature1 = "nFeature_RNA", feature2 = "percent.mito")
FeatureScatter(organoids.seurat, feature1="nFeature_RNA", feature2="percent.ribo")

##Remove mitochondrial, ribosomal, no ENTREZID and lowly expressed genes + low quality cells that have low RNA content as well as few detected genes
chuck <- unique(c(mito,ribo,missingEZID,which(rownames(organoids.seurat)=="MALAT1")))
length(chuck)
organoids.seurat <- organoids.seurat[-chuck,]
ann <- ann[-chuck,]
table(ann$SYMBOL==rownames(organoids.seurat))

#remove genes having 0 count in more than 20 cells -> minimum size of a cluster can be 20 cells.
numzero.genes <- rowSums(organoids.seurat@assays$RNA@counts==0)
table(numzero.genes > (ncol(organoids.seurat)-20))
keep.genes <- numzero.genes < (ncol(organoids.seurat)-20)
table(keep.genes)
organoids.seurat <- organoids.seurat[keep.genes,]
dim(organoids.seurat)
ann <- ann[keep.genes,]

#remove low quality cells
organoids.seurat <- subset(organoids.seurat, subset = nCount_RNA > 2500 & nFeature_RNA > 500)
dim(organoids.seurat)
#16142  2566
#check the distribution again
par(mfrow=c(1,3))
plot(density(organoids.seurat$nCount_RNA),main="Distribution of library sizes")
abline(v=2500,col=2)
legend("topright",lty=2,col=4,legend="2500 library size")
plot(density(organoids.seurat$proportion.zeroes), main="Distribution of proportion of zeroes per cell", cex.main=1)
abline(v=0.95,col=2)
legend("topright",lty=2,col=4,legend="0.95 proportion of zeroes/cell")
plot(density(organoids.seurat$nFeature_RNA), main="Distribution of detected genes per cell", cex.main=1)
abline(v=500,col=4, lty=3)
legend("topright",lty=2,col=4,legend="500 genes")

##Nomralize
organoids.seurat <- SCTransform(organoids.seurat, verbose = FALSE)
organoids.seurat <- NormalizeData(organoids.seurat, normalization.method = "LogNormalize", scale.factor = 10000)
organoids.seurat <- FindVariableFeatures(organoids.seurat, selection.method = "vst", nfeatures = 2000)
bulkgenes <- read.delim("./bulkRNA.txt",sep=",", row.names = 1, as.is = TRUE)
intersect.genes <- intersect(bulkgenes[,1],organoids.seurat@assays$RNA@var.features)
write.csv(intersect.genes, "./intersectGENES.txt")
all.genes <- rownames(organoids.seurat)
organoids.seurat <- ScaleData(organoids.seurat, features = all.genes, do.center = TRUE) # scaled all features reason: https://satijalab.org/seurat/v3.0/pbmc3k_tutorial.html

#Plot variable features ( Mean variance plpot for genes)
top_10 <- organoids.seurat@assays$SCT@var.features[1:10]
plot1 <- VariableFeaturePlot(organoids.seurat)
plot2 <- LabelPoints(plot = plot1, points = top_10, repel = TRUE, xnudge = 0, ynudge = 0)


##Run PCA and cluster cells
set.seed(10)
organoids.seurat <- RunPCA(organoids.seurat, npcs = 50,features = intersect.genes , approx = FALSE)
write.csv(organoids.seurat@reductions[["pca"]]@feature.loadings[,1:2],"./PCA-geneloading.csv")
organoids.seurat <- RunPCA(organoids.seurat,npcs=50, verbose = FALSE)

pdf(file="./geneloading.pdf",width=20,height=15,onefile = FALSE)
par(mfrow=c(1,1))
par(mar = c(5,5,3,1))
PCA_data <- data.frame(PC1 = organoids.seurat@reductions[["pca"]]@cell.embeddings[,1], PC2 = organoids.seurat@reductions[["pca"]]@cell.embeddings[,2], cluster = organoids.seurat@meta.data[["RNA_snn_res.0.3"]])
geneLoading <- data.frame(PC1 = organoids.seurat@reductions[["pca"]]@feature.loadings[,1], PC2 = organoids.seurat@reductions[["pca"]]@feature.loadings[,2])
ggplot(geneLoading,mapping = aes(PC1,PC2 , label = rownames(geneLoading))) +geom_point(size = 2, shape = 21,colour = 'black', fill = "lightgray") + theme_bw() +geom_text_repel() #+xlim(-25,50) + ylim(-40,10)
dev.off()

par(mfrow =c(1,1))
plot1 <- plot(geneLoading)
plot2 <- LabelPoints(plot = plot1, points = rownames(geneLoading), repel = TRUE, xnudge = 0, ynudge = 0)
plot(organoids.seurat@reductions[["pca"]]@cell.embeddings[,1],organoids.seurat@reductions[["pca"]]@cell.embeddings[,2], col = "red")
DimPlot(organoids.seurat, reduction = "pca", dims = c(1,2), label = T)
DimHeatmap(organoids.seurat, dims = 2, cells = 500,nfeatures = 30, balanced = TRUE)
ElbowPlot(organoids.seurat,ndims=50)
set.seed(10)
organoids.seurat <- RunUMAP(organoids.seurat, dims = 1:30, verbose = FALSE)
organoids.seurat <- FindNeighbors(organoids.seurat, dims = 1:30, verbose = FALSE)
organoids.seurat<- FindClusters(organoids.seurat, resolution = 0.3, verbose = FALSE)
clusres <- c(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,1.1,1.2)
for(i in 1:length(clusres)){
  organoids.seurat<- FindClusters(organoids.seurat, resolution = clusres[i], verbose = FALSE)
}
clustree(organoids.seurat, prefix = "SCT_snn_res.")
Idents(organoids.seurat) <- organoids.seurat@meta.data$RNA_snn_res.0.1
DimPlot(organoids.seurat, reduction = "umap", label = T)
Idents(organoids.seurat) <- organoids.seurat@meta.data$SCT_snn_res.0.2
organoids.markers <- FindAllMarkers(organoids.seurat, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
top20 <- organoids.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
write.csv(top20,file="./top20-clustermarkers.csv")
DefaultAssay(organoids.seurat) <- "SCT"
organoids.seurat <- RenameIdents(organoids.seurat, `0` = "CM1", `1` = "CM2", `2` = "CM3", `3` = "Proliferative", `4` = "Fibroblast")

library(RColorBrewer)  
display.brewer.all()
brewer.pal(n = 9, name = "Blues")
o <- organoids.seurat
FeaturePlot(organoids.seurat, features = c("TNNT2","MYH7","E2F1", "COL1A2","VWF","PECAM1","ENG","EMCN"), pt.size = 0.2, ncol = 2, label = T)
VlnPlot(organoids.seurat,features = c("EEF1A1","EEF1A2","TNNT2","MYH6"),same.y.lims = T, ncol = 2)

#Limma trend for DE-------------------------
organoid.dgList <- DGEList(counts = organoids.seurat@assays$RNA@counts, genes = rownames(organoids.seurat@assays$RNA))
logcounts <- normCounts(organoid.dgList,log=TRUE,prior.count=0.5)
maxclust <- length(levels(Idents(organoids.seurat)))-1
grp <- paste("c",Idents(organoids.seurat),sep = "")
grp <- factor(grp,levels = paste("c",0:maxclust,sep=""))
design <- model.matrix(~0+grp)
colnames(design) <- levels(grp)
mycont <- matrix(NA,ncol=length(levels(grp)),nrow=length(levels(grp)))
rownames(mycont)<-colnames(mycont)<-levels(grp)
diag(mycont)<-1
mycont[upper.tri(mycont)]<- -1/(length(levels(factor(grp)))-1)
mycont[lower.tri(mycont)]<- -1/(length(levels(factor(grp)))-1)
fit <- lmFit(logcounts,design)
fit.cont <- contrasts.fit(fit,contrasts=mycont)
fit.cont <- eBayes(fit.cont,trend=TRUE,robust=TRUE)
fit.cont$genes <- rownames(organoids.seurat)
summary(decideTests(fit.cont))
treat <- treat(fit.cont,lfc=0.5)
treat$ENTREZID <- ann$ENTREZID[match(treat$genes,ann$SYMBOL)]
dt<-decideTests(treat)
summary(dt)
par(mfrow=c(2,3))
for(i in 1:ncol(mycont)){
  plotMD(treat,coef=i,status = dt[,i],hl.cex=0.5)
  abline(h=0,col=colours()[c(226)])
  lines(lowess(treat$Amean,treat$coefficients[,i]),lwd=1.5,col=4)
}

contnames <- colnames(mycont)

for(i in 1:length(contnames)){
  topsig <- topTreat(treat,coef=i,n=Inf,p.value=0.05)
  topsig$ENTREZID <- ann$ENTREZID[match(topsig$ID,ann$SYMBOL)]
  write.csv(topsig[topsig$logFC>0.5,],file=paste("./organoids.up-Cluster-",contnames[i],".csv",sep=""))
  write.csv(topGO(goana(de=topsig$ENTREZID[topsig$logFC>0.5],universe=treat$ENTREZID,species="Hs"),number=50),
            file=paste("./GO-Cluster-",contnames[i],".csv",sep=""))
  
}

par(las=2) # make label text perpendicular to axis
par(mar=c(5,15,4,2)) # increase y-axis margin.
GO_0 <- GO_Cluster_c2 %>% filter(GO_Cluster_c2$Ont=="BP")
GO_0_selected <- GO_0 %>% select(c(Term,P.DE,DE))
bp <- barplot(GO_0_selected$DE[10:1], horiz = T, names.arg = GO_0_selected$Term[10:1], cex.names=0.8, cex.axis = 0.8, xlim = c(0,250))
title(main = "Top 10 significant Biological Processes in Proliferative", xlab = "#Genes in DE list")

#take just cardiomyocytes:
organoids <- organoids.seurat[,which(organoids.seurat@meta.data$RNA_snn_res.0.2 %in% c(0,1,2,3))]

DimPlot(organoids.seurat, reduction = "pca", label = TRUE, label.size = 6, dims = c(1,2)) + NoLegend()
FeaturePlot(organoids.seurat, features = c("TNNT2", "MYH6", "ACTN2", "WT1", "TBX3", "PDGFRA","PECAM1","COL1A2","TAGLN"), pt.size = 0.2, ncol = 3)
par(mfrow=c(1,1))
barplot(table(Idents(organoids.seurat)),ylab="Number of cells",xlab="Clusters", ylim = c(0,2000))
title("Number of cells in each cluster res 0.2")

##Heatmap of predefined heart cell type markers
hm <- read.delim("./Heart_Marker_ES",sep = "",stringsAsFactors = FALSE, header = TRUE)
hgene <- toupper(hm$genes)
hgene <- unique(hgene)
DefaultAssay(organoids.seurat) <- "RNA"
log_counts <- normCounts(DGEList(organoids.seurat@assays$RNA@counts),log=TRUE,prior.count=0.5)
m <- match(hgene,rownames(organoids.seurat))
m <- m[!is.na(m)]
maxclust <- length(levels(Idents(organoids.seurat)))-1
grp <- Idents(organoids.seurat$SCT_snn_res.0.3)
grp <- factor(grp,levels = paste("c",0:maxclust,sep=""))
o <- order(grp)
mycelltypes <- hm$cellType[match(rownames(organoids.seurat)[m],toupper(hm$genes))]
mycelltypes <- factor(mycelltypes)

mygenes <- rownames(organoids.seurat)[m]
mygenelab <- paste(mygenes,mycelltypes,sep="_")

myColors <- list(Clust=NA,Celltypes=NA)
myColors$Clust<- ggplotColors(maxclust + 1)
names(myColors$Clust)<-levels(grp)
n <- nlevels(mycelltypes)
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
myColors$Celltypes <- col_vector[1:n]
names(myColors$Celltypes) <- levels(mycelltypes)
pdf(file="./heatmap-hmarkers-summarised.pdf",width=20,height=15,onefile = FALSE)
par(mfrow=c(1,1))
aheatmap(log_counts[m,o],Rowv=NA,Colv=NA,labRow=mygenelab,labCol=NA,
         annCol=list(Clust=grp[o]),
         annRow = list(Celltypes=mycelltypes),
         annColors = myColors, 
         fontsize=7,color="-RdYlBu", cexRow = 3)
dev.off()